from distutils.core import setup

setup(
    name='Pro5',
    version='',
    packages=['Venv.lib.python3.6.distutils', 'Venv.lib.python3.6.encodings', 'Venv.lib.python3.6.importlib',
              'Venv.lib.python3.6.collections', 'Venv.lib.python3.6.site-packages.pip',
              'Venv.lib.python3.6.site-packages.pip.req', 'Venv.lib.python3.6.site-packages.pip.vcs',
              'Venv.lib.python3.6.site-packages.pip.utils', 'Venv.lib.python3.6.site-packages.pip.compat',
              'Venv.lib.python3.6.site-packages.pip.models', 'Venv.lib.python3.6.site-packages.pip._vendor',
              'Venv.lib.python3.6.site-packages.pip._vendor.distlib',
              'Venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'Venv.lib.python3.6.site-packages.pip._vendor.colorama',
              'Venv.lib.python3.6.site-packages.pip._vendor.html5lib',
              'Venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'Venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'Venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'Venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'Venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'Venv.lib.python3.6.site-packages.pip._vendor.lockfile',
              'Venv.lib.python3.6.site-packages.pip._vendor.progress',
              'Venv.lib.python3.6.site-packages.pip._vendor.requests',
              'Venv.lib.python3.6.site-packages.pip._vendor.requests.packages',
              'Venv.lib.python3.6.site-packages.pip._vendor.requests.packages.chardet',
              'Venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3',
              'Venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.util',
              'Venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'Venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'Venv.lib.python3.6.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'Venv.lib.python3.6.site-packages.pip._vendor.packaging',
              'Venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'Venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'Venv.lib.python3.6.site-packages.pip._vendor.webencodings',
              'Venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'Venv.lib.python3.6.site-packages.pip.commands', 'Venv.lib.python3.6.site-packages.pip.operations',
              'Venv.lib.python3.6.site-packages.pytz', 'Venv.lib.python3.6.site-packages.numpy',
              'Venv.lib.python3.6.site-packages.numpy.ma', 'Venv.lib.python3.6.site-packages.numpy.doc',
              'Venv.lib.python3.6.site-packages.numpy.fft', 'Venv.lib.python3.6.site-packages.numpy.lib',
              'Venv.lib.python3.6.site-packages.numpy.core', 'Venv.lib.python3.6.site-packages.numpy.f2py',
              'Venv.lib.python3.6.site-packages.numpy.compat', 'Venv.lib.python3.6.site-packages.numpy.linalg',
              'Venv.lib.python3.6.site-packages.numpy.random', 'Venv.lib.python3.6.site-packages.numpy.testing',
              'Venv.lib.python3.6.site-packages.numpy.distutils',
              'Venv.lib.python3.6.site-packages.numpy.distutils.command',
              'Venv.lib.python3.6.site-packages.numpy.distutils.fcompiler',
              'Venv.lib.python3.6.site-packages.numpy.matrixlib', 'Venv.lib.python3.6.site-packages.numpy.polynomial',
              'Venv.lib.python3.6.site-packages.scipy', 'Venv.lib.python3.6.site-packages.scipy.io',
              'Venv.lib.python3.6.site-packages.scipy.io.arff', 'Venv.lib.python3.6.site-packages.scipy.io.matlab',
              'Venv.lib.python3.6.site-packages.scipy.io.harwell_boeing', 'Venv.lib.python3.6.site-packages.scipy.odr',
              'Venv.lib.python3.6.site-packages.scipy._lib', 'Venv.lib.python3.6.site-packages.scipy.misc',
              'Venv.lib.python3.6.site-packages.scipy.stats', 'Venv.lib.python3.6.site-packages.scipy.linalg',
              'Venv.lib.python3.6.site-packages.scipy.signal', 'Venv.lib.python3.6.site-packages.scipy.sparse',
              'Venv.lib.python3.6.site-packages.scipy.sparse.linalg',
              'Venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen',
              'Venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.arpack',
              'Venv.lib.python3.6.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'Venv.lib.python3.6.site-packages.scipy.sparse.linalg.dsolve',
              'Venv.lib.python3.6.site-packages.scipy.sparse.linalg.isolve',
              'Venv.lib.python3.6.site-packages.scipy.sparse.csgraph', 'Venv.lib.python3.6.site-packages.scipy.cluster',
              'Venv.lib.python3.6.site-packages.scipy.fftpack', 'Venv.lib.python3.6.site-packages.scipy.ndimage',
              'Venv.lib.python3.6.site-packages.scipy.spatial', 'Venv.lib.python3.6.site-packages.scipy.special',
              'Venv.lib.python3.6.site-packages.scipy.special._precompute',
              'Venv.lib.python3.6.site-packages.scipy.optimize', 'Venv.lib.python3.6.site-packages.scipy.optimize._lsq',
              'Venv.lib.python3.6.site-packages.scipy.constants', 'Venv.lib.python3.6.site-packages.scipy.integrate',
              'Venv.lib.python3.6.site-packages.scipy.interpolate',
              'Venv.lib.python3.6.site-packages.scipy._build_utils', 'Venv.lib.python3.6.site-packages.wheel',
              'Venv.lib.python3.6.site-packages.wheel.test',
              'Venv.lib.python3.6.site-packages.wheel.test.simple.dist.simpledist',
              'Venv.lib.python3.6.site-packages.wheel.test.complex-dist.complexdist',
              'Venv.lib.python3.6.site-packages.wheel.tool', 'Venv.lib.python3.6.site-packages.wheel.signatures',
              'Venv.lib.python3.6.site-packages.branca', 'Venv.lib.python3.6.site-packages.folium',
              'Venv.lib.python3.6.site-packages.folium.plugins', 'Venv.lib.python3.6.site-packages.jinja2',
              'Venv.lib.python3.6.site-packages.pandas', 'Venv.lib.python3.6.site-packages.pandas.io',
              'Venv.lib.python3.6.site-packages.pandas.io.sas', 'Venv.lib.python3.6.site-packages.pandas.io.tests',
              'Venv.lib.python3.6.site-packages.pandas.io.tests.json',
              'Venv.lib.python3.6.site-packages.pandas.io.tests.parser', 'Venv.lib.python3.6.site-packages.pandas.api',
              'Venv.lib.python3.6.site-packages.pandas.api.tests', 'Venv.lib.python3.6.site-packages.pandas.api.types',
              'Venv.lib.python3.6.site-packages.pandas.rpy', 'Venv.lib.python3.6.site-packages.pandas.core',
              'Venv.lib.python3.6.site-packages.pandas.util', 'Venv.lib.python3.6.site-packages.pandas.util.clipboard',
              'Venv.lib.python3.6.site-packages.pandas.stats', 'Venv.lib.python3.6.site-packages.pandas.stats.tests',
              'Venv.lib.python3.6.site-packages.pandas.tests', 'Venv.lib.python3.6.site-packages.pandas.tests.frame',
              'Venv.lib.python3.6.site-packages.pandas.tests.types',
              'Venv.lib.python3.6.site-packages.pandas.tests.series',
              'Venv.lib.python3.6.site-packages.pandas.tests.formats',
              'Venv.lib.python3.6.site-packages.pandas.tests.indexes',
              'Venv.lib.python3.6.site-packages.pandas.tests.plotting',
              'Venv.lib.python3.6.site-packages.pandas.tests.test_msgpack',
              'Venv.lib.python3.6.site-packages.pandas.tools', 'Venv.lib.python3.6.site-packages.pandas.tools.tests',
              'Venv.lib.python3.6.site-packages.pandas.types', 'Venv.lib.python3.6.site-packages.pandas.compat',
              'Venv.lib.python3.6.site-packages.pandas.compat.numpy', 'Venv.lib.python3.6.site-packages.pandas.sparse',
              'Venv.lib.python3.6.site-packages.pandas.sparse.tests', 'Venv.lib.python3.6.site-packages.pandas.formats',
              'Venv.lib.python3.6.site-packages.pandas.indexes', 'Venv.lib.python3.6.site-packages.pandas.msgpack',
              'Venv.lib.python3.6.site-packages.pandas.tseries',
              'Venv.lib.python3.6.site-packages.pandas.tseries.tests',
              'Venv.lib.python3.6.site-packages.pandas.computation',
              'Venv.lib.python3.6.site-packages.pandas.computation.tests', 'Venv.lib.python3.6.site-packages.seaborn',
              'Venv.lib.python3.6.site-packages.seaborn.tests', 'Venv.lib.python3.6.site-packages.seaborn.external',
              'Venv.lib.python3.6.site-packages.dateutil', 'Venv.lib.python3.6.site-packages.dateutil.tz',
              'Venv.lib.python3.6.site-packages.dateutil.zoneinfo', 'Venv.lib.python3.6.site-packages.packaging',
              'Venv.lib.python3.6.site-packages.markupsafe', 'Venv.lib.python3.6.site-packages.matplotlib',
              'Venv.lib.python3.6.site-packages.matplotlib.tri', 'Venv.lib.python3.6.site-packages.matplotlib.axes',
              'Venv.lib.python3.6.site-packages.matplotlib.style', 'Venv.lib.python3.6.site-packages.matplotlib.tests',
              'Venv.lib.python3.6.site-packages.matplotlib.compat',
              'Venv.lib.python3.6.site-packages.matplotlib.testing',
              'Venv.lib.python3.6.site-packages.matplotlib.testing.jpl_units',
              'Venv.lib.python3.6.site-packages.matplotlib.backends',
              'Venv.lib.python3.6.site-packages.matplotlib.backends.qt_editor',
              'Venv.lib.python3.6.site-packages.matplotlib.delaunay',
              'Venv.lib.python3.6.site-packages.matplotlib.sphinxext',
              'Venv.lib.python3.6.site-packages.matplotlib.sphinxext.tests',
              'Venv.lib.python3.6.site-packages.matplotlib.projections', 'Venv.lib.python3.6.site-packages.setuptools',
              'Venv.lib.python3.6.site-packages.setuptools.command',
              'Venv.lib.python3.6.site-packages.mpl_toolkits.tests',
              'Venv.lib.python3.6.site-packages.mpl_toolkits.mplot3d',
              'Venv.lib.python3.6.site-packages.mpl_toolkits.axes_grid',
              'Venv.lib.python3.6.site-packages.mpl_toolkits.axes_grid1',
              'Venv.lib.python3.6.site-packages.mpl_toolkits.axisartist',
              'Venv.lib.python3.6.site-packages.pkg_resources'],
    url='',
    license='',
    author='TheKingNat',
    author_email='',
    description='Terrorist Attack Analysis'
)
